# Generated by Django 4.2.13 on 2024-06-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajos', '0002_alter_trabajo_fecha_termino'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoImpresion3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trabajos.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('superior', 'Superior'), ('inferior', 'Inferior'), ('ambos', 'Ambos'), ('hemiarcada', 'Hemiarcada')], max_length=20)),
                ('trabajo_impresion3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='impresion3d.trabajoimpresion3d')),
            ],
        ),
        migrations.CreateModel(
            name='GuiaQuirurgica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('trabajo_impresion3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_quirurgicas', to='impresion3d.trabajoimpresion3d')),
            ],
        ),
        migrations.CreateModel(
            name='Biomodelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('trabajo_impresion3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomodelos', to='impresion3d.trabajoimpresion3d')),
            ],
        ),
    ]
