# Generated by Django 4.2.13 on 2024-06-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='tipo_pieza',
            field=models.CharField(choices=[('1.1', '1.1'), ('1.1', '1.2')], max_length=50),
        ),
    ]
