# docker-compose.yml
version: '3.8'

services:
  web:
    build: ./app
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/tuimagen_lab:/app
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/tuimagen_lab/staticfiles:/app/static
      # - ./nginx/letsencrypt:/etc/letsencrypt  # Montar el volumen de los certificados
    depends_on:
      - web
    restart: unless-stopped