version: '3.8'

services:
  web:
    build: ./app
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/tuimagen_lab:/app
    #ports:
      #- "8000:8000"
    env_file:
      - ./app/.env
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - tuimagen_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/tuimagen_lab/staticfiles:/app/static
      # - ./nginx/letsencrypt:/etc/letsencrypt  # Montar el volumen de los certificados
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - tuimagen_net

  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tuimagen_lab
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: unless-stopped
    networks:
      - tuimagen_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - tuimagen_net

volumes:
  mysql-data:

networks:
  tuimagen_net:
    driver: bridge
