version: '3.9'

services:
  web:
    container_name: web
    build: ./app
    command: >
      sh -c "pipenv run python manage.py migrate &&
             pipenv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/tuimagen_lab:/app
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - tuimagen_net

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/tuimagen_lab/staticfiles:/app/static
      # - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - tuimagen_net

  db:
    container_name: db
    image: mysql:8.0
    volumes:
      - ./mysql-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - tuimagen_net

  phpmyadmin:
    container_name: phpmyadmin
    image: linuxserver/phpmyadmin
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - tuimagen_net

volumes:
  mysql-data:

networks:
  tuimagen_net:
    driver: bridge
