# Generated by Django 4.2.13 on 2024-06-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_material_nombre_alter_pieza_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='EN_PROCESO', max_length=20),
        ),
    ]
