# Generated by Django 5.0.6 on 2024-06-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_pieza_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(choices=[('Feldesfato', 'Feldesfato'), ('Disilicato', 'Disilicato')], max_length=100),
        ),
    ]
