# Generated by Django 5.0.6 on 2024-06-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_material_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='nombre',
            field=models.CharField(max_length=5),
        ),
    ]
