# Generated by Django 4.2.13 on 2024-06-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=20),
        ),
    ]
