# Generated by Django 4.2.13 on 2024-06-11 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_entrega', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('terminado', 'Terminado')], default='en_proceso', max_length=20)),
                ('tipo_trabajo', models.CharField(choices=[('fresado', 'Fresado'), ('impresion_3d', 'Impresión 3D'), ('escaneo_intraoral', 'Escaneo Intraoral')], max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
