# Generated by Django 4.2.13 on 2024-06-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_termino',
            field=models.DateField(null=True),
        ),
    ]
