# Generated by Django 4.2.13 on 2024-06-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
        ('trabajos', '0002_alter_trabajo_fecha_termino'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='doctores.doctor')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajos.trabajo')),
            ],
        ),
    ]
