# Generated by Django 4.2.13 on 2024-06-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0003_trabajodoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajodoctor',
            name='fecha_pago',
            field=models.DateField(null=True),
        ),
    ]
